services:
  luthfullah-website:
    image: node:18-alpine
    container_name: luthfullah-container
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8081:3000"  # Map your VPS Port 8081 to Next.js Port 3000
    command: >
      sh -c "npm install && npm run build && npm start"
